#!/bin/sh
# $Id$
exec rlwrap -b "'\"(){}[],#|\\" gosh "$@"
#exec rlwrap -b "'\"(){}[],#|\\" /usr/local/gauche/bin/gosh "$@"
#exec rlwrap -b "'\"(){}[],#|\\" -f /usr/local/gauche/share/gosh_completions gosh "$@"
# vim:set ft=sh sw=2 ts=2 et:
