#!/bin/sh
# $Id$

BASENAME=Gauche-tir

while [ $# -gt 0 ]; do
  case $1 in
    gen) gen=yes; shift ;;
    tgz) gen=yes; tgz=yes; shift ;;
    *) echo "DIST [gen|tgz]"; exit 0;;
  esac
done

if [ "$gen" = "yes" ]; then
  autoconf -I `gauche-config --ac`
  ./configure || (echo "cannot execute ./configure"; exit 1)
  gosh gen-version VERSION > lib/tir/version.scm
  make distclean
fi


if [ "$tgz" = "yes" ]; then
  if [ ! -f VERSION ]; then echo "no VERSION -- something wrong?"; exit 1; fi
  ./configure || (echo "cannot execute ./configure"; exit 1)
  make distclean
  VERSION=`cat VERSION`
  DIR_NAME=${BASENAME}-${VERSION}
  rm -rf ../${DIR_NAME} ../${DIR_NAME}.tgz
  rm -f DIST_EXCLUDE_X
  cat DIST_EXCLUDE > DIST_EXCLUDE_X
  find . -name CVS -print -prune >> DIST_EXCLUDE_X
  find . -name .svn -print -prune >> DIST_EXCLUDE_X

  mkdir ../${DIR_NAME}
  tar -cv -f - -X DIST_EXCLUDE_X . | (cd ../${DIR_NAME}; tar xf -)
  (cd ..; tar cvf - ${DIR_NAME} | gzip -9 > ${DIR_NAME}.tgz)
  rm -rf ../${DIR_NAME}
fi

